#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

gitleaks

#
# a sneaky test for myself to ensure that
# my contributions remain outside of work hours
#

# work hours file detected
# perform verification
if test -f .hidden/.noworkinworkhours; then
  # work hour specification variables
  WORK_DAYS=("1" "2" "3" "4" "5")
  WORK_HOURS_MIN="09:00"
  WORK_HOURS_MAX="17:00"
  # pull current time variables
  DAY=$(date +%u)
  TIME=$(date +%H:%M)
  # print an initial header
  echo "-- Verifying $TIME is outside of work hours"
  echo "-- Work days - ${WORK_DAYS[*]}"
  echo "-- Work hours min time - $WORK_HOURS_MIN"
  echo "-- Work hours max time - $WORK_HOURS_MAX"
  # check if the commit is on a work day
  if [[ "${WORK_DAYS[*]}" =~ " ${DAY} " ]]; then
    # check if the commit is within work hours
    # use negation to obtain -ge and -le functionality
    if ! [[ "$TIME" < "$WORK_HOURS_MIN" ]] && ! [[ "$TIME" > "$WORK_HOURS_MAX" ]]; then
      # work day work hours detected, fail the verification
      >&2 echo "-- Error: Work hours detected"
      exit 1
    fi
  fi
  # print a success message
  echo "-- Success: Work hours not detected"
# no work hours file detected
# do not perform verification
else
  # print an informative message
  echo "-- Skipping commit work hours verification"
fi